version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: alby-albyhub_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"
  server:
    image: ghcr.io/getalby/hub:v1.18.5
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${UMBREL_ROOT}/app-data/lightning/data/lnd:/lnd:ro
    environment:
      LN_BACKEND_TYPE: ${APP_ALBYHUB_LN_BACKEND:-LDK}
      LND_ADDRESS: ${APP_ALBYHUB_LND_ADDRESS}
      LND_CERT_FILE: ${APP_ALBYHUB_LND_CERT_FILE}
      LND_MACAROON_FILE: ${APP_ALBYHUB_LND_MACAROON_FILE}
      WORK_DIR: "/data/albyhub"
      COOKIE_SECRET: "742375a0f444d6de9c692aa83ac43c10"
      LOG_EVENTS: "true"
    restart: on-failure
    stop_grace_period: 1m
